\documentclass{article}

\begin{document}

\section*{Ebola virus Epidemic}

<<Chunk1, echo=FALSE>>=
library("rvest") # loading package "rvest" to read data from html web pagesinto the current session.
ebolaVirusData <- html("http://en.wikipedia.org/wiki/Ebola_virus_epidemic_in_West_Africa") # Parsing the html page.
dataFrame <- html_table(html_nodes(ebolaVirusData, "table")[[2]]) #Parsing table into data farme.
dataFrame
@

The World Health Organization (WHO) and respective governments have reported a total of \Sexpr{24632} suspected cases and \Sexpr{10159} deaths,though the WHO believes that this substantially understates the magnitude of the outbreak. In the United States there has been \Sexpr{4} reported cases and \Sexpr{1} deaths.

\end{document}